info: BEGIN SESSION : start {"timestamp":"2024-02-20 21:58:52"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 21:58:52"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 21:58:52"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 21:58:52"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:01:10"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:01:10"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:01:10"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:01:10"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:01:34"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:01:34"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:01:41"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:01:41"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:01:41"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:01:41"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:02:32"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:02:32"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:02:32"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:02:32"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:02:50"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:02:50"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:02:50"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:02:50"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:03:15"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:03:15"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:03:15"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:03:15"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:04:01"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:04:01"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:04:01"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:04:01"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:04:20"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:04:20"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:04:20"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:04:20"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:04:35"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:04:35"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:04:35"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:04:35"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:07:02"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:07:02"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 ./matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/./matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:07:02"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 ./matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/./matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:07:02"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:07:41"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:07:41"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 001-MatrixDiagonalization/matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/001-MatrixDiagonalization/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:07:41"}
error: ERROR SESSION : start = Erreur lors de l'exécution du script Python : Error: Command failed: python3 001-MatrixDiagonalization/matrixDiag.py  start
python3: can't open file '/home/zenemis/Desktop/SapientiaProject/SapientiaBack/001-MatrixDiagonalization/matrixDiag.py': [Errno 2] No such file or directory

 {"timestamp":"2024-02-20 22:07:41"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:08:04"}
info: BEGIN SESSION : start {"timestamp":"2024-02-20 22:08:04"}
INFO:root:Generating matrix diag with seed 314846
INFO:root:Beggining generation of matrix
INFO:root:Generating matrix diag with seed 534182
INFO:root:Beggining generation of matrix
INFO:root:generateMatrix | Generated D matrix : Matrix([[-3/2, 0, 0], [0, -5/2, 0], [0, 0, 1]])
INFO:root:generateMatrix | Generated D matrix : Matrix([[2, 0, 0], [0, -1/2, 0], [0, 0, -3]])
INFO:root:generateMatrix | Generated P matrix : Matrix([[-2, -2, -4], [-1, 5, -3], [-2, 5, 0]])
INFO:root:generateMatrix | Generated P matrix : Matrix([[1, 5, 2], [-4, -2, 4], [-4, -1, -5]])
INFO:root:generateMatrix | Generated M matrix : Matrix([[-71/87, -305/348, 5/29], [50/87, -47/174, 70/29], [95/87, 935/348, -12/29]])
INFO:root:generateMatrix | Returning generation of matrix
INFO:root:generateMatrix | Generated M matrix : Matrix([[-55/62, 78/31, -58/31], [135/124, -14/31, -50/31], [15/31, -20/31, -103/62]])
INFO:root:generateMatrix | Returning generation of matrix
info: END SESSION : start = [object Object] of type object
 {"timestamp":"2024-02-20 22:08:04"}
info: END SESSION : start = [object Object] of type object
 {"timestamp":"2024-02-20 22:08:04"}
